name:  synchro-repo
on:
  push:
    branches:
      - v6
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
        
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Deploy
        env:
           MESSAGEDATA: ${{ github.event.head_commit.message }}
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: v6
          commit-message: ${{ env.MESSAGEDATA }}
          folder: .
          repository-name: 'Five-great/tinymce-plugin-docs'
